Repository TransparentPath/buildly-react-template, pull requests merged in 2021-05, with the labels that each got.

#175 Added expiration time on alerts for 24 hours
  src/pages/Shipment/AlertInfo.js
Labels: enhancement

#174 Shipment Popup - Data loss prevention and redux cache persistence issue
  src/pages/Items/forms/AddItems.js
  src/pages/Reporting/Reporting.js
  src/pages/SensorsGateway/Sensors/SearchModal.js
  src/pages/Shipment/AlertInfo.js
  src/pages/Shipment/ShipmentConstants.js
  src/pages/Shipment/components/EnvironmentalLimitsInfo.js
  src/pages/Shipment/components/ItemInfo.js
  src/pages/Shipment/components/Sensors&GatewayInfo.js
  src/pages/Shipment/components/ShipmentInfo.js
  src/pages/Shipment/components/ShipmentKeyInfo.js
  src/pages/Shipment/components/ShipmentRouteInfo.js
  src/pages/Shipment/components/custodian-info/AddCustodyForm.js
  src/pages/Shipment/components/custodian-info/CustodianInfo.js
  src/pages/Shipment/forms/AddShipment.js
  src/redux/reducers.js
  src/utils/mediaQuery.js
Labels: re-opened

#182 fix showing custodian name in the form
  src/pages/Shipment/components/custodian-info/AddCustodyForm.js
Labels: bug

#183 Custody popup on form submit check validation
  src/pages/Shipment/components/custodian-info/AddCustodyForm.js
Labels: bug

#186 Updated the display logic according to tive values
  src/pages/Reporting/ReportingConstants.js
  src/pages/Shipment/Shipment.js
  src/pages/Shipment/ShipmentConstants.js
Labels: bug

#188 Correct temperature units for tive sensors
  src/pages/Reporting/ReportingConstants.js
  src/pages/Shipment/Shipment.js
Labels: bug

#184 Refactoring Code 2
  src/components/DataTableWrapper/DataTableWrapper.js
  src/components/Modal/Modal.js
  src/components/SearchComponent/SearchInput.js
  src/components/Table/Table.js
  src/pages/AdminPanel/Configuration/components/CustodianType.js
  src/pages/AdminPanel/Configuration/components/GatewayType.js
  src/pages/AdminPanel/Configuration/components/ItemType.js
  src/pages/AdminPanel/Configuration/components/Product.js
  src/pages/AdminPanel/Configuration/components/ProductType.js
  src/pages/AdminPanel/Configuration/components/SensorType.js
  src/pages/AdminPanel/Configuration/components/ShipmentFlag.js
  src/pages/AdminPanel/Configuration/components/UnitOfMeasure.js
  src/pages/Dashboard/Dashboard.js
  src/pages/Dashboard/DashboardConstants.js
  src/pages/MyAccount/MyAccount.js
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/ReportingConstants.js
  src/pages/Reporting/components/SensorReport.js
  src/pages/SensorsGateway/forms/AddGateway.js
  src/pages/Shipment/AlertInfo.js
  src/pages/Shipment/Shipment.js
  src/pages/Shipment/ShipmentConstants.js
  src/pages/Shipment/components/EnvironmentalLimitsInfo.js
  src/pages/Shipment/components/ItemInfo.js
  src/pages/Shipment/components/Sensors&GatewayInfo.js
  src/pages/Shipment/components/ShipmentDataTable.js
  src/pages/Shipment/components/ShipmentInfo.js
  src/pages/Shipment/components/ShipmentKeyInfo.js
  src/pages/Shipment/components/ShipmentOverview.js
  src/pages/Shipment/components/ShipmentRouteInfo.js
  src/pages/Shipment/components/ViewDetailsWrapper.js
  src/pages/Shipment/components/custodian-info/AddCustodyForm.js
  src/pages/Shipment/components/custodian-info/CustodianInfo.js
  src/pages/Shipment/forms/AddDestinationInfo.js
  src/pages/Shipment/forms/AddOriginInfo.js
  src/pages/Shipment/forms/AddShipment.js
  src/pages/Shipment/forms/AddShipperInfo.js
Labels: enhancement

#191 Feedback issues 1
  src/pages/AdminPanel/ImportExport/forms/AddFromAPI.js
  src/pages/Custodians/Custodians.js
  src/pages/Custodians/forms/AddCustodians.js
  src/pages/Items/Items.js
  src/pages/Items/forms/AddItems.js
  src/pages/MyAccount/forms/EditProfileInfo.js
  src/pages/Reporting/ReportingConstants.js
  src/pages/SensorsGateway/Sensors/Sensors.js
  src/pages/SensorsGateway/forms/AddGateway.js
  src/pages/SensorsGateway/forms/AddSensors.js
  src/pages/Shipment/components/EnvironmentalLimitsInfo.js
  src/pages/Shipment/components/ShipmentInfo.js
  src/pages/Shipment/components/custodian-info/AddCustodyForm.js
  src/pages/Shipment/components/custodian-info/CustodianInfo.js
  src/redux/shipment/actions/shipment.actions.js
  src/redux/shipment/sagas/shipment.saga.js
Labels: bug, enhancement

#193 fix alerts display
  src/modules/oauth/oauth.service.js
  src/pages/Shipment/AlertInfo.js
Labels: bug

#197 Feedback Bugs and Enhancements - 2
  src/layout/TopBar/TopBar.js
  src/pages/AdminPanel/Configuration/ConfigurationConstants.js
  src/pages/AdminPanel/Configuration/components/CustodianType.js
  src/pages/AdminPanel/Configuration/components/GatewayType.js
  src/pages/AdminPanel/Configuration/components/ItemType.js
  src/pages/AdminPanel/Configuration/components/Product.js
  src/pages/AdminPanel/Configuration/components/ProductType.js
  src/pages/AdminPanel/Configuration/components/SensorType.js
  src/pages/AdminPanel/Configuration/components/ShipmentFlag.js
  src/pages/AdminPanel/Configuration/components/UnitOfMeasure.js
  src/pages/Custodians/CustodianConstants.js
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/ReportingConstants.js
  src/pages/Shipment/AlertInfo.js
  src/pages/Shipment/Shipment.js
  src/pages/Shipment/ShipmentConstants.js
  src/pages/Shipment/components/Sensors&GatewayInfo.js
  src/pages/Shipment/components/ShipmentDataTable.js
  src/pages/Shipment/components/ShipmentInfo.js
  src/pages/Shipment/components/ShipmentKeyInfo.js
  src/pages/Shipment/components/custodian-info/AddCustodyForm.js
  src/redux/options/actions/options.actions.js
  src/redux/options/reducers/options.reducer.js
  src/redux/shipment/sagas/shipment.saga.js
Labels: bug, enhancement

#200 Change timezone switch to select field
  src/layout/TopBar/TopBar.js
Labels: enhancement

#202 multiple timezone support
  package.json
  src/components/GraphComponent/GraphComponent.js
  src/layout/TopBar/TopBar.js
  src/pages/AdminPanel/Configuration/ConfigurationConstants.js
  src/pages/AdminPanel/Configuration/components/CustodianType.js
  src/pages/AdminPanel/Configuration/components/GatewayType.js
  src/pages/AdminPanel/Configuration/components/ItemType.js
  src/pages/AdminPanel/Configuration/components/Product.js
  src/pages/AdminPanel/Configuration/components/ProductType.js
  src/pages/AdminPanel/Configuration/components/SensorType.js
  src/pages/AdminPanel/Configuration/components/ShipmentFlag.js
  src/pages/AdminPanel/Configuration/components/UnitOfMeasure.js
  src/pages/Items/ItemsConstants.js
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/ReportingConstants.js
  src/pages/Reporting/components/SensorReport.js
  src/pages/SensorsGateway/Constants.js
  src/pages/SensorsGateway/Gateway/Gateway.js
  src/pages/SensorsGateway/Sensors/Sensors.js
  src/pages/SensorsGateway/forms/AddGateway.js
  src/pages/SensorsGateway/forms/AddSensors.js
  src/pages/Shipment/AlertInfo.js
  src/pages/Shipment/Shipment.js
  src/pages/Shipment/ShipmentConstants.js
  src/pages/Shipment/components/Sensors&GatewayInfo.js
  src/pages/Shipment/components/ShipmentDataTable.js
  src/pages/Shipment/components/ShipmentInfo.js
  src/pages/Shipment/components/custodian-info/AddCustodyForm.js
  src/pages/Shipment/components/custodian-info/CustodianInfo.js
  src/pages/Shipment/forms/AddShipment.js
  src/redux/options/actions/options.actions.js
  src/redux/options/reducers/options.reducer.js
Labels: enhancement

#203 Excursion, Warning, Recovery Alerts
  src/modules/oauth/oauth.service.js
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/ReportingConstants.js
  src/pages/Reporting/components/AlertsReport.js
  src/pages/Shipment/AlertInfo.js
  src/pages/Shipment/Shipment.js
  src/pages/Shipment/ShipmentConstants.js
  src/redux/sensorsGateway/actions/sensorsGateway.actions.js
  src/redux/sensorsGateway/actions/sensorsGateway.actions.test.js
  src/redux/sensorsGateway/reducers/sensorsGateway.reducer.js
  src/redux/sensorsGateway/reducers/sensorsGateway.reducer.test.js
  src/redux/sensorsGateway/sagas/sensorsGateway.saga.js
  src/redux/shipment/actions/shipment.actions.js
  src/redux/shipment/actions/shipment.actions.test.js
  src/redux/shipment/reducers/shipment.reducers.js
  src/redux/shipment/reducers/shipment.reducers.test.js
  src/redux/shipment/sagas/shipment.saga.js
Labels: enhancement
