Repository TransparentPath/buildly-react-template, pull requests merged in 2021-04, with the labels that each got.

#146 Alerts session maintenance
  src/midgard/modules/oauth/oauth.service.js
  src/midgard/pages/Shipment/AlertInfo.js
  src/midgard/redux/shipment/sagas/shipment.saga.js
Labels: enhancement

#147 Fixes for graph rendering
  src/midgard/components/GraphComponent/GraphComponent.js
  src/midgard/utils/utilMethods.js
Labels: bug

#150 Tive sensor platform integration
  src/midgard/components/MapComponent/MapComponent.js
  src/midgard/pages/SensorsGateway/Constants.js
  src/midgard/pages/Shipment/ShipmentConstants.js
  src/midgard/pages/Shipment/components/Sensors&GatewayInfo.js
  src/midgard/pages/Shipment/components/ShipmentInfo.js
  src/midgard/redux/shipment/sagas/shipment.saga.js
  src/midgard/utils/mock.js
Labels: Story/ Sub Feature

#151 Patch - Show status field for gateways then show shipment name with a link add that to the list of gateways
  src/midgard/components/DashboardWrapper/DashboardWrapper.js
  src/midgard/pages/Custodians/forms/AddCustodians.js
  src/midgard/pages/Items/forms/AddItems.js
  src/midgard/pages/SensorsGateway/Constants.js
  src/midgard/pages/SensorsGateway/Gateway/Gateway.js
  src/midgard/pages/SensorsGateway/Sensors/Sensors.js
  src/midgard/pages/SensorsGateway/SensorsGateway.js
  src/midgard/pages/SensorsGateway/forms/AddGateway.js
  src/midgard/pages/Shipment/components/Sensors&GatewayInfo.js
Labels: enhancement

#153 Unique Identifier and PDF upload for a shipment
  package.json
  src/midgard/components/Loader/Loader.js
  src/midgard/pages/Shipment/components/PDFViewer.js
  src/midgard/pages/Shipment/components/ShipmentInfo.js
  src/midgard/pages/Shipment/components/ShipmentKeyInfo.js
  src/midgard/pages/Shipment/forms/AddShipment.js
  src/midgard/redux/shipment/actions/shipment.actions.js
  src/midgard/redux/shipment/reducers/shipment.reducers.js
  src/midgard/redux/shipment/sagas/shipment.saga.js
Labels: enhancement

#156 Rectified platform name for gateway selection
  src/midgard/pages/Shipment/components/Sensors&GatewayInfo.js
Labels: bug

#165 Feedback fixes enhancements
  src/pages/Custodians/CustodianConstants.js
  src/pages/Custodians/forms/AddCustodians.js
  src/pages/Items/ItemsConstants.js
  src/pages/Items/forms/AddItems.js
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/ReportingConstants.js
  src/pages/SensorsGateway/Constants.js
  src/pages/Shipment/Shipment.js
  src/pages/Shipment/ShipmentConstants.js
  src/pages/Shipment/components/ItemInfo.js
  src/pages/Shipment/components/ShipmentInfo.js
  src/pages/Shipment/components/custodian-info/AddCustodyForm.js
  src/redux/shipment/sagas/shipment.saga.js
  src/utils/utilMethods.js
Labels: bug, enhancement

#167 Remove org uuid from sensor report calls
  src/environments/environment.dev.js
  src/environments/environment.js
  src/environments/environment.prod.js
  src/pages/Dashboard/Dashboard.js
  src/pages/Reporting/Reporting.js
  src/pages/Shipment/Shipment.js
  src/redux/sensorsGateway/actions/sensorsGateway.actions.js
  src/redux/sensorsGateway/actions/sensorsGateway.actions.test.js
  src/redux/sensorsGateway/sagas/sensorsGateway.saga.js
  src/redux/shipment/actions/shipment.actions.js
  src/redux/shipment/actions/shipment.actions.test.js
  src/redux/shipment/sagas/shipment.saga.js
  window.environment.js
Labels: enhancement

#169 Geofence Alerts - Custody Ordering
  src/pages/Shipment/AlertInfo.js
  src/pages/Shipment/ShipmentConstants.js
  src/pages/Shipment/components/custodian-info/AddCustodyForm.js
  src/pages/Shipment/components/custodian-info/CustodianInfo.js
  src/utils/utilMethods.js
Labels: bug
