Repository TransparentPath/buildly-react-template, pull requests merged in 2022-03, with the labels that each got.

#301 Add functionality to remove custodian from a shipment
  src/pages/Shipment/components/custodian-info/CustodianInfo.js
  src/redux/custodian/actions/custodian.actions.js
  src/redux/custodian/reducers/custodian.reducer.js
  src/redux/custodian/sagas/custodian.saga.js
Labels: enhancement

#308 Feedback for Acceptance testing - v0.4.8
  src/pages/SensorsGateway/Constants.js
  src/pages/Shipment/ShipmentConstants.js
  src/pages/Shipment/components/ShipmentDataTable.js
  src/pages/Shipment/components/custodian-info/CustodianInfo.js
  src/redux/custodian/sagas/custodian.saga.js
  src/styles/theme.js
Labels: feedback

#306 Feat#303/Update To Refresh - SW
  package.json
  src/index.js
  src/serviceWorkerRegistration.js
  src/styles/theme.js
  webpack.config.js
Labels: enhancement

#314 Admin Panel Scroll Issue & Core User's Organization Name Bug
  src/pages/AdminPanel/Configuration/Configuration.js
  src/pages/AdminPanel/Consortium/ConsortiumSettings.js
  src/pages/AdminPanel/ImportExport/ImportExport.js
  src/pages/UserManagement/Users/Users.js
  src/styles/theme.js
Labels: bug

#315 Update shipment redux when updates happen on custody
  package.json
  src/pages/SensorsGateway/Constants.js
  src/pages/Shipment/Shipment.js
  src/pages/Shipment/ShipmentConstants.js
  src/redux/custodian/reducers/custodian.reducer.js
  src/redux/custodian/sagas/custodian.saga.js
  src/redux/shipment/sagas/shipment.saga.js
Labels: feedback

#322 Prevent refreshing custodians when new shipment created
  src/redux/custodian/sagas/custodian.saga.js
  src/redux/shipment/sagas/shipment.saga.js
Labels: bug, feedback

#324 Show custodian and aggregate report on initial load
  src/redux/shipment/sagas/shipment.saga.js
Labels: bug
