Repository TransparentPath/buildly-react-template, pull requests merged in 2024-10, with the labels that each got.

#501 Update Trackers UI and fix some issues
  src/components/MapComponent/MapComponent.js
  src/components/MapComponent/MapComponentStyles.css
  src/pages/Login/Login.js
  src/pages/Register/Register.js
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/components/GenerateReport.js
  src/pages/ResetPassword/EmailForm.js
  src/pages/SensorsGateway/Gateway.js
  src/pages/SensorsGateway/GatewayStyles.css
  src/pages/SensorsGateway/forms/AddGateway.js
  src/pages/SensorsGateway/forms/AddShipper.js
  src/pages/Shipment/CreateShipment.js
  src/pages/UserManagement/forms/AddOrganization.js
  src/pages/UserManagement/forms/AddUser.js
  src/react-query/mutations/notifications/reportPDFDownloadMutation.js
  src/styles/theme.js
  src/utils/constants.js
  src/utils/validators.js
  src/zustand/reportPdf/reportPdfStore.js
Labels: bug, enhancement

#504 Add Trackers UI
  src/components/Alert/AlertStyles.css
  src/components/DataTableWrapper/DataTableWrapper.js
  src/components/DataTableWrapper/DataTableWrapperStyles.css
  src/components/OrganizationSelector/OrganizationSelector.js
  src/components/OrganizationSelector/OrganizationSelectorStyles.css
  src/layout/TopBar/AccountMenu.js
  src/layout/TopBar/TopBar.js
  src/layout/TopBar/components/AccountSettings.js
  src/pages/AdminPanel/AdminPanel.js
  src/pages/AdminPanel/AdminPanelStyles.css
  src/pages/AdminPanel/Trackers/TrackerSettings.js
  src/pages/AdminPanel/Trackers/forms/Devices.js
  src/pages/Register/Register.js
  src/pages/Reporting/components/ReportingDetailTable.js
  src/pages/SensorsGateway/Gateway.js
  src/pages/SensorsGateway/GatewayStyles.css
  src/pages/SensorsGateway/components/GatewayActions.js
  src/pages/SensorsGateway/forms/AddGateway.js
  src/pages/Shipment/CreateShipment.js
  src/pages/Shipment/Shipment.js
  src/react-query/mutations/sensorGateways/editGatewayMutation.js
  src/react-query/mutations/sensorGateways/fetchNewGatewayMutation.js
  src/react-query/mutations/sensorGateways/syncGatewayMutation.js
  src/routes/routesConstants.js
  src/utils/constants.js
  src/utils/mock.js
Labels: enhancement

#507 Added changes
  initialize_container.sh
  package.json
  src/components/OrganizationSelector/OrganizationSelector.js
  src/layout/TopBar/TopBar.js
  src/pages/AdminPanel/AdminPanel.js
  src/pages/AdminPanel/Invoices/Invoices.js
  src/pages/AdminPanel/Invoices/InvoicesStyles.css
  src/pages/Custodians/CustodianStyles.css
  src/pages/Custodians/forms/AddCustodians.js
  src/pages/SensorsGateway/Gateway.js
  src/pages/SensorsGateway/GatewayStyles.css
  src/pages/SensorsGateway/components/GatewayActions.js
  src/pages/SensorsGateway/forms/AddShipper.js
  src/react-query/mutations/notifications/whatsappChargesMutation.js
  src/react-query/mutations/trackerorder/editTrackerOrderMutation.js
  src/routes/routesConstants.js
  src/styles/theme.js
  src/utils/mock.js
  webpack.config.js
Labels: enhancement

#508 Feedback fixes and charts
  package.json
  src/components/DataTableWrapper/DataTableWrapper.js
  src/components/GraphComponent/GraphComponent.css
  src/components/GraphComponent/GraphComponent.js
  src/hooks/useInput.js
  src/pages/AdminPanel/AdminPanel.js
  src/pages/AdminPanel/Configuration/components/RecipientAddress.js
  src/pages/AdminPanel/Configuration/forms/AddRecipientAddress.js
  src/pages/AdminPanel/TrackerOrder/TrackerOrder.js
  src/pages/AdminPanel/TrackerOrder/TrackerOrderStyles.css
  src/pages/AdminPanel/TrackerOrder/forms/AddTrackerOrder.js
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/ReportingStyles.css
  src/pages/Reporting/components/ReportGraph.js
  src/routes/routesConstants.js
  src/utils/constants.js
  src/zustand/cart/cartStore.js
Labels: bug
