Repository TransparentPath/buildly-react-template, pull requests merged in 2024-11, with the labels that each got.

#510 Fix/translation
  initialize_container.sh
  src/components/CustomizedStepper/CustomizedStepper.js
  src/components/OrganizationSelector/OrganizationSelector.js
  src/layout/TopBar/TopBar.js
  src/modules/oauth/oauth.service.js
  src/pages/AdminPanel/Configuration/components/OrganizationSettings.js
  src/pages/AdminPanel/Invoices/Invoices.js
  src/pages/AdminPanel/Invoices/InvoicesStyles.css
  src/pages/AdminPanel/TrackerOrder/TrackerOrderStyles.css
  src/pages/AdminPanel/TrackerOrder/forms/AddTrackerOrder.js
  src/pages/AdminPanel/Trackers/forms/Devices.js
  src/pages/Custodians/forms/AddCustodians.js
  src/pages/SensorsGateway/Gateway.js
  src/pages/SensorsGateway/components/GatewayActions.js
  src/pages/SensorsGateway/forms/AddShipper.js
  src/pages/Shipment/CreateShipment.js
  src/react-query/queries/sensorGateways/getGatewayQuery.js
  src/styles/theme.js
  src/utils/constants.js
Labels: bug, enhancement

#514 Fix issues
  src/pages/AdminPanel/Invoices/Invoices.js
  src/pages/AdminPanel/Invoices/InvoicesStyles.css
  src/pages/Reporting/Reporting.js
  src/pages/SensorsGateway/Gateway.js
  src/pages/SensorsGateway/GatewayStyles.css
  src/pages/SensorsGateway/components/GatewayActions.js
  src/utils/mock.js
Labels: bug, enhancement

#515 Fix country names
  src/react-query/queries/shipments/getCountriesQuery.js
Labels: enhancement

#517 fix reseller customer dropdown
  src/pages/UserManagement/forms/AddResellers.js
Labels: bug
