Repository TransparentPath/buildly-react-template, pull requests merged in 2024-05, with the labels that each got.

#441 Production patch v1.3.1
  initialize_container.sh
  package.json
  src/pages/SensorsGateway/forms/AddGateway.js
Labels: deployment

#440 Feat/whatsapp sms alerts
  package.json
  src/layout/TopBar/TopBarStyles.css
  src/layout/TopBar/components/AccountSettings.js
  src/pages/Register/Register.js
  src/pages/Register/RegisterStyles.css
Labels: enhancement

#443 Fix battery level in shipment section
  initialize_container.sh
  src/pages/Shipment/Shipment.js
  src/react-query/queries/notifications/getVersionNotesQuery.js
  src/utils/constants.js
Labels: bug

#444 Production Release v1.3.1
  initialize_container.sh
  package.json
  src/layout/TopBar/TopBarStyles.css
  src/layout/TopBar/components/AccountSettings.js
  src/layout/TopBar/components/WhatsNew/WhatsNewContent.js
  src/layout/TopBar/components/WhatsNew/WhatsNewFooter.js
  src/layout/TopBar/components/WhatsNew/WhatsNewHeader.js
  src/layout/TopBar/components/WhatsNew/WhatsNewModal.js
  src/layout/TopBar/components/WhatsNew/WhatsNewSlider.js
  src/pages/Register/Register.js
  src/pages/Register/RegisterStyles.css
  src/pages/Shipment/Shipment.js
  src/react-query/queries/notifications/getVersionNotesQuery.js
  src/utils/constants.js
Labels: deployment

#445 Production release v1.3.2
  .github/workflows/prod-build.yml
  initialize_container.sh
  package.json
  src/index.html
  src/layout/TopBar/TopBar.js
  src/layout/TopBar/components/WhatsNew/WhatsNewHeader.js
  src/pages/AboutPlatform/AboutPlatform.js
  webpack.config.js
  window.environment.js
Labels: deployment

#446 Merge Demo to Master
  .github/workflows/demo-build.yml
  .github/workflows/prod-build.yml
  initialize_container.sh
  package.json
  src/components/DataTableWrapper/DataTableWrapper.js
  src/components/GraphComponent/GraphComponent.js
  src/index.html
  src/layout/TopBar/TopBar.js
  src/layout/TopBar/TopBarStyles.css
  src/layout/TopBar/components/AccountSettings.js
  src/layout/TopBar/components/AlertNotifications.js
  src/layout/TopBar/components/WhatsNew/WhatsNewContent.js
  src/layout/TopBar/components/WhatsNew/WhatsNewFooter.js
  src/layout/TopBar/components/WhatsNew/WhatsNewHeader.js
  src/layout/TopBar/components/WhatsNew/WhatsNewModal.js
  src/layout/TopBar/components/WhatsNew/WhatsNewSlider.js
  src/pages/AboutPlatform/AboutPlatform.js
  src/pages/Register/Register.js
  src/pages/Register/RegisterStyles.css
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/components/SensorReport.js
  src/pages/SensorsGateway/forms/AddGateway.js
  src/pages/Shipment/CreateShipment.js
  src/pages/Shipment/Shipment.js
  src/react-query/mutations/shipments/addShipmentMutation.js
  src/react-query/mutations/shipments/editShipmentMutation.js
  src/react-query/queries/notifications/getVersionNotesQuery.js
  src/utils/constants.js
  webpack.config.js
  window.environment.js
Labels: deployment

#450 Feat/minor UI changes
  src/components/MapComponent/MapComponent.js
  src/pages/SensorsGateway/Gateway.js
  src/pages/Shipment/CreateShipment.js
  src/pages/Shipment/Shipment.js
  src/pages/Shipment/ShipmentStyles.css
  src/react-query/mutations/sensorGateways/deleteGatewayMutation.js
  src/utils/constants.js
  src/utils/mock.js
Labels: enhancement

#452 Completed to Cancelled, Battery Depleted, Damaged
  package.json
  src/pages/Shipment/CreateShipment.js
Labels: bug

#455 Add resellers-customers, localization and guidance text
  initialize_container.sh
  package.json
  src/i18n.js
  src/index.html
  src/index.js
  src/layout/TopBar/TopBar.js
  src/layout/TopBar/TopBarStyles.css
  src/pages/AdminPanel/Configuration/components/OrganizationSettings.js
  src/pages/Shipment/CreateShipment.js
  src/pages/Shipment/ShipmentStyles.css
  src/pages/UserManagement/UserManagement.js
  src/pages/UserManagement/UserManagementStyles.css
  src/pages/UserManagement/forms/AddOrganization.js
  src/pages/UserManagement/forms/AddResellers.js
  src/pages/UserManagement/forms/AddUser.js
  src/react-query/mutations/authUser/inviteMutation.js
  src/react-query/mutations/authUser/loginMutation.js
  src/react-query/mutations/authUser/updateOrganizationMutation.js
  src/react-query/mutations/authUser/updateUserMutation.js
  src/utils/mock.js
  webpack.config.js
Labels: enhancement

#456 Demo release v1.4.0
  .github/workflows/dev-build.yml
  initialize_container.sh
  package.json
  src/components/MapComponent/MapComponent.js
  src/i18n.js
  src/index.html
  src/index.js
  src/layout/TopBar/TopBar.js
  src/layout/TopBar/TopBarStyles.css
  src/pages/AdminPanel/Configuration/components/OrganizationSettings.js
  src/pages/SensorsGateway/Gateway.js
  src/pages/Shipment/CreateShipment.js
  src/pages/Shipment/Shipment.js
  src/pages/Shipment/ShipmentStyles.css
  src/pages/UserManagement/UserManagement.js
  src/pages/UserManagement/UserManagementStyles.css
  src/pages/UserManagement/forms/AddOrganization.js
  src/pages/UserManagement/forms/AddResellers.js
  src/pages/UserManagement/forms/AddUser.js
  src/react-query/mutations/authUser/inviteMutation.js
  src/react-query/mutations/authUser/loginMutation.js
  src/react-query/mutations/authUser/updateOrganizationMutation.js
  src/react-query/mutations/authUser/updateUserMutation.js
  src/react-query/mutations/sensorGateways/deleteGatewayMutation.js
  src/utils/constants.js
  src/utils/mock.js
  webpack.config.js
Labels: deployment
