Repository TransparentPath/buildly-react-template, pull requests merged in 2024-08, with the labels that each got.

#474 UI/reporting
  initialize_container.sh
  package.json
  src/components/DataTableWrapper/DataTableWrapper.js
  src/components/DataTableWrapper/DataTableWrapperStyles.css
  src/components/GraphComponent/GraphComponent.js
  src/components/MapComponent/MapComponent.js
  src/layout/TopBar/AccountMenu.js
  src/layout/TopBar/TopBar.js
  src/layout/TopBar/components/AccountSettings.js
  src/modules/http/http.service.js
  src/pages/AdminPanel/Configuration/components/GatewayType.js
  src/pages/AdminPanel/Configuration/forms/AddGatewayType.js
  src/pages/Custodians/forms/AddCustodians.js
  src/pages/Items/forms/AddItems.js
  src/pages/Register/Register.js
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/ReportingStyles.css
  src/pages/Reporting/components/AlertsReport.js
  src/pages/Reporting/components/GenerateReport.js
  src/pages/Reporting/components/ReportGraph.js
  src/pages/Reporting/components/ReportingActiveShipmentDetails.js
  src/pages/Reporting/components/ReportingDetailTable.js
  src/pages/Reporting/components/SensorReport.js
  src/pages/SensorsGateway/forms/AddGateway.js
  src/pages/Shipment/CreateShipment.js
  src/pages/Shipment/Shipment.js
  src/pages/UserManagement/forms/AddResellers.js
  src/pages/UserManagement/forms/AddUser.js
  src/react-query/mutations/notifications/reportPDFDownloadMutation.js
  src/react-query/queries/sensorGateways/getSensorProcessedDataQuery.js
  src/styles/theme.js
  src/utils/constants.js
  src/utils/utilMethods.js
Labels: enhancement

#475 Demo deployment
  .github/workflows/demo-build.yml
  .github/workflows/dev-build.yml
  .github/workflows/prod-build.yml
  initialize_container.sh
  package.json
  src/components/DataTableWrapper/DataTableWrapper.js
  src/components/DataTableWrapper/DataTableWrapperStyles.css
  src/components/GraphComponent/GraphComponent.js
  src/components/MapComponent/MapComponent.js
  src/layout/TopBar/AccountMenu.js
  src/layout/TopBar/TopBar.js
  src/layout/TopBar/components/AccountSettings.js
  src/modules/http/http.service.js
  src/pages/AdminPanel/Configuration/components/GatewayType.js
  src/pages/AdminPanel/Configuration/forms/AddGatewayType.js
  src/pages/Custodians/forms/AddCustodians.js
  src/pages/Items/forms/AddItems.js
  src/pages/Register/Register.js
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/ReportingStyles.css
  src/pages/Reporting/components/AlertsReport.js
  src/pages/Reporting/components/GenerateReport.js
  src/pages/Reporting/components/ReportGraph.js
  src/pages/Reporting/components/ReportingActiveShipmentDetails.js
  src/pages/Reporting/components/ReportingDetailTable.js
  src/pages/Reporting/components/SensorReport.js
  src/pages/SensorsGateway/forms/AddGateway.js
  src/pages/Shipment/CreateShipment.js
  src/pages/Shipment/Shipment.js
  src/pages/UserManagement/forms/AddResellers.js
  src/pages/UserManagement/forms/AddUser.js
  src/react-query/mutations/notifications/reportPDFDownloadMutation.js
  src/react-query/queries/sensorGateways/getSensorProcessedDataQuery.js
  src/styles/theme.js
  src/utils/constants.js
  src/utils/utilMethods.js
Labels: deployment

#478 Fix issues
  src/layout/TopBar/TopBar.js
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/components/GenerateReport.js
  src/pages/Reporting/components/ReportMap.js
  src/pages/Reporting/components/ReportingActiveShipmentDetails.js
  src/pages/Reporting/components/ReportingDetailTable.js
  src/pages/Shipment/CreateShipment.js
  src/pages/Shipment/Shipment.js
  src/pages/Shipment/ShipmentStyles.css
  src/react-query/mutations/notifications/reportPDFDownloadMutation.js
  src/utils/constants.js
  src/zustand/reportPdf/reportPdfStore.js
Labels: bug

#479 Demo deployment
  src/layout/TopBar/TopBar.js
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/components/GenerateReport.js
  src/pages/Reporting/components/ReportMap.js
  src/pages/Reporting/components/ReportingActiveShipmentDetails.js
  src/pages/Reporting/components/ReportingDetailTable.js
  src/pages/Shipment/CreateShipment.js
  src/pages/Shipment/Shipment.js
  src/pages/Shipment/ShipmentStyles.css
  src/react-query/mutations/notifications/reportPDFDownloadMutation.js
  src/utils/constants.js
  src/zustand/reportPdf/reportPdfStore.js
Labels: deployment

#481 Fix/feedback issues
  src/components/MapComponent/MapComponent.js
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/components/GenerateReport.js
  src/pages/Reporting/components/ReportGraph.js
  src/pages/Reporting/components/ReportMap.js
  src/react-query/mutations/notifications/reportPDFDownloadMutation.js
Labels: bug, enhancement

#484 Fix issues
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/ReportingStyles.css
Labels: bug, enhancement

#485 Demo deployment
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/ReportingStyles.css
Labels: deployment

#486 Demo deployment
  src/components/MapComponent/MapComponent.js
  src/modules/http/http.service.js
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/ReportingStyles.css
  src/pages/Reporting/components/AlertsReport.js
  src/pages/Reporting/components/GenerateReport.js
  src/pages/Reporting/components/ReportGraph.js
  src/pages/Reporting/components/ReportMap.js
  src/pages/Reporting/components/ReportingDetailTable.js
  src/react-query/mutations/notifications/reportPDFDownloadMutation.js
  src/utils/constants.js
Labels: deployment
