Repository TransparentPath/buildly-react-template, pull requests merged in 2024-09, with the labels that each got.

#488 Reporting/issues
  package.json
  public/index.html
  src/components/DataTableWrapper/DataTableWrapperStyles.css
  src/components/MapComponent/MapComponent.js
  src/index.html
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/ReportingStyles.css
  src/pages/Reporting/components/AlertsReport.js
  src/pages/Reporting/components/GenerateReport.js
  src/pages/Reporting/components/ReportGraph.js
  src/pages/Reporting/components/ReportingDetailTable.js
  src/utils/constants.js
  src/utils/utilMethods.js
Labels: bug

#491 fix issues
  src/layout/TopBar/TopBar.js
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/components/AlertsReport.js
  src/pages/Reporting/components/ReportingDetailTable.js
  src/pages/Shipment/CreateShipment.js
  src/pages/UserManagement/forms/AddResellers.js
  src/pages/UserManagement/forms/AddUser.js
Labels: enhancement

#492 Fix issues
  src/components/MapComponent/MapComponent.js
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/components/AlertsReport.js
  src/pages/Reporting/components/ReportingDetailTable.js
  src/utils/constants.js
Labels: bug, enhancement

#494 Fix map
  initialize_container.sh
  package.json
  src/components/MapComponent/MapComponent.js
  src/pages/Reporting/Reporting.js
  src/pages/SensorsGateway/forms/AddGateway.js
  src/pages/Shipment/CreateShipment.js
  src/pages/Shipment/Shipment.js
  src/pages/Shipment/ShipmentStyles.css
  src/utils/utilMethods.js
Labels: bug, enhancement

#496 Fix csv excel files
  src/pages/Reporting/Reporting.js
Labels: bug

#498 Feat/bulk custodian upload
  initialize_container.sh
  package.json
  src/components/DataTableWrapper/DataTableWrapper.js
  src/components/DataTableWrapper/DataTableWrapperStyles.css
  src/pages/Custodians/Custodians.js
  src/react-query/mutations/custodians/uploadBulkCustodianMutation.js
Labels: enhancement
