Repository TransparentPath/buildly-react-template, pull requests merged in 2024-04, with the labels that each got.

#422 Feat/custodians
  package.json
  src/assets/tp-logo.png
  src/index.html
  src/layout/TopBar/TopBarStyles.css
  src/layout/TopBar/components/AlertNotifications.js
  src/pages/Custodians/Custodians.js
  src/pages/SensorsGateway/forms/AddGateway.js
  src/pages/Shipment/CreateShipment.js
  src/styles/theme.js
  src/utils/constants.js
Labels: enhancement

#425 Feat/whatsnew
  src/components/DataTableWrapper/DataTableWrapper.js
  src/layout/TopBar/AccountMenu.js
  src/layout/TopBar/TopBar.js
  src/layout/TopBar/TopBarStyles.css
  src/layout/TopBar/components/WhatsNew/WhatsNewContent.js
  src/layout/TopBar/components/WhatsNew/WhatsNewFooter.js
  src/layout/TopBar/components/WhatsNew/WhatsNewHeader.js
  src/layout/TopBar/components/WhatsNew/WhatsNewModal.js
  src/layout/TopBar/components/WhatsNew/WhatsNewSlider.js
  src/modules/http/http.service.js
  src/pages/AdminPanel/Configuration/Configuration.js
  src/pages/AdminPanel/Configuration/components/GatewayType.js
  src/pages/AdminPanel/Configuration/forms/AddGatewayType.js
  src/pages/Login/Login.js
  src/pages/Login/LoginStyles.css
  src/pages/ResetPassword/Verification.js
  src/pages/SensorsGateway/Gateway.js
  src/pages/SensorsGateway/forms/AddGateway.js
  src/pages/Shipment/CreateShipment.js
  src/pages/Shipment/Shipment.js
  src/pages/UserManagement/forms/AddUser.js
  src/react-query/mutations/sensorGateways/addGatewayMutation.js
  src/react-query/mutations/sensorGateways/addGatewayTypeMutation.js
  src/react-query/mutations/sensorGateways/deleteGatewayMutation.js
  src/react-query/mutations/sensorGateways/deleteGatewayTypeMutation.js
  src/react-query/mutations/sensorGateways/editGatewayMutation.js
  src/react-query/mutations/sensorGateways/editGatewayTypeMutation.js
  src/react-query/mutations/shipments/editShipmentMutation.js
  src/react-query/queries/notifications/getVersionNotesQuery.js
  src/react-query/queries/sensorGateways/getAllGatewayQuery.js
  src/react-query/queries/sensorGateways/getGatewayQuery.js
  src/react-query/queries/sensorGateways/getGatewayTypeQuery.js
  src/serviceWorkerRegistration.js
  src/utils/constants.js
  src/utils/mock.js
Labels: bug, enhancement

#427 Fix issues
  src/components/MapComponent/MapComponent.js
  src/layout/TopBar/TopBar.js
Labels: enhancement

#431 Multiple enhancements changes
  src/components/GraphComponent/GraphComponent.js
  src/pages/Reporting/Reporting.js
  src/pages/Shipment/CreateShipment.js
  src/utils/constants.js
Labels: enhancement

#432 fix manual shipment status update
  src/pages/Shipment/CreateShipment.js
  src/react-query/mutations/shipments/addShipmentMutation.js
  src/react-query/mutations/shipments/editShipmentMutation.js
  src/utils/constants.js
Labels: bug

#436 Fix timezone issue
  src/layout/TopBar/components/AlertNotifications.js
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/components/SensorReport.js
  src/pages/Shipment/Shipment.js
  src/utils/constants.js
Labels: enhancement
