Repository TransparentPath/buildly-react-template, pull requests merged in 2024-02, with the labels that each got.

#393 Fix UI issues
  src/components/MapComponent/MapComponent.js
  src/layout/TopBar/TopBarStyles.css
  src/layout/TopBar/components/AccountSettings.js
  src/layout/TopBar/components/AlertNotifications.js
  src/pages/AdminPanel/AdminPanelStyles.css
  src/pages/AdminPanel/Configuration/components/OrganizationSettings.js
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/ReportingStyles.css
  src/pages/Reporting/components/AlertsReport.js
  src/pages/Reporting/components/SensorReport.js
  src/react-query/mutations/shipments/addShipmentMutation.js
  src/react-query/mutations/shipments/editShipmentMutation.js
Labels: bug, enhancement

#399 Fix issues
  src/components/CustomizedStepper/CustomizedStepper.js
  src/components/CustomizedStepper/CustomizedStepperStyles.css
  src/pages/Reporting/Reporting.js
  src/pages/Reporting/components/SensorReport.js
  src/pages/Shipment/Shipment.js
Labels: enhancement

#401 Fix issues
  src/components/CustomizedStepper/CustomizedStepper.js
  src/pages/Reporting/Reporting.js
  src/react-query/queries/shipments/getShipmentsQuery.js
Labels: bug, enhancement

#411 Production release v1.2.2
  package.json
  src/react-query/mutations/authUser/loginMutation.js
  src/react-query/mutations/shipments/addShipmentMutation.js
  src/react-query/mutations/shipments/editShipmentMutation.js
Labels: deployment
